---

packages:
  - mysql-server=5.7.*
  - python3-mysqldb
  - python-pymysql

mysql:
  root_db_password: pASSWORD123123$
  hosts:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
