---

packages:
  - mysql-server=5.7.*
  - python3-mysqldb
  - python-pymysql

mysql:
  user: root
  old_password: root
  new_password: 123123
  root_db_password: pASSWORD123123$
  hosts:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
  privileges: "*.*:ALL,GRANT"
