---

- name: Install MySQL and packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"
  tags:
    - mysql


- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  tags: [ mysql ]


- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name:                 root
    host:                 "{{ item }}"
    login_unix_socket:    /var/run/mysqld/mysqld.sock
    password:             "{{ mysql.root_db_password }}"
    priv:                 '*.*:ALL,GRANT'
    check_implicit_admin: true
  loop: "{{ mysql.hosts }}"
  become: yes
  notify: Restart MySQL
  tags: [ mysql ]


- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart MySQL
  tags:
    - mysql


- name: Remove all anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent
  notify: Restart MySQL
  tags:
    - mysql
